<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net10.0;net6.0;</TargetFrameworks>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<DocumentationFile>bin\$(MSBuildProjectName).xml</DocumentationFile>
		<DefineConstants>LuceneSharp;SmallDict;</DefineConstants>
		<RootAllConstants>LuceneSharp;TfidfAndPosSeg;SmallDict;BigDict</RootAllConstants>
		<RootNamespace>JiebaNet</RootNamespace>		
		<!-- nuget -->
		<Description>支持.net10的Jieba分词</Description>
		<PackRelease>true</PackRelease>
		<PackageProjectUrl>https://github.com/lozye/JiebaSharp</PackageProjectUrl>
		<RepositoryUrl>https://github.com/lozye/JiebaSharp</RepositoryUrl>
		<RepositoryType>github</RepositoryType>
		<Authors>Lozye</Authors>
		<Company>Lozye</Company>
		<Version>1.0.0.2</Version>
		<IncludeContentInPack>true</IncludeContentInPack>
		<PackageReadmeFile>$(ProjectDir)\readme.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<Nuget>false</Nuget>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="..\Analyser\**\*.cs" Exclude="**\obj\**\*.cs;**\bin\**\*.cs" LinkBase="Analyser" />
		<Compile Include="..\Segmenter\**\*.cs" Exclude="**\obj\**\*.cs;**\bin\**\*.cs" LinkBase="Segmenter" />
		<Compile Remove="**\ConfigManager.cs" />
		<Compile Remove="**\WordDictionary.cs" />
		<Compile Remove="**\DefaultDictionary.cs" />
		<Compile Remove="**\Spelling\*.cs" />
		<Compile Remove="**\FileExtension.cs" />
		
		<!-- 资源文件 -->
		<Content Include="..\Resources\standard\*.*" LinkBase="Resources\JiebaSharp" Pack="true">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<PackagePath>contentFiles\any\any\Resources\JiebaSharp</PackagePath>			
			<PackageCopyToOutput>true</PackageCopyToOutput>
		</Content>
		<Content Include="..\Resources\posseg\*.*" LinkBase="Resources\JiebaSharp" Pack="true" Condition="'$(DefineConstants.Contains(`TfidfAndPosSeg`))'">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<PackagePath>contentFiles\any\any\Resources\JiebaSharp</PackagePath>
			<PackageCopyToOutput>true</PackageCopyToOutput>
		</Content>
		<Content Include="..\Resources\dict_small\*.*" LinkBase="Resources\JiebaSharp" Pack="true" Condition="'$(DefineConstants.Contains(`SmallDict`))'">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<PackagePath>contentFiles\any\any\Resources\JiebaSharp</PackagePath>
			<PackageCopyToOutput>true</PackageCopyToOutput>
		</Content>
		<Content Include="..\Resources\dict_big\*.*" LinkBase="Resources\JiebaSharp" Pack="true" Condition="'$(DefineConstants.Contains(`BigDict`))'">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<PackagePath>contentFiles\any\any\Resources\JiebaSharp</PackagePath>
			<PackageCopyToOutput>true</PackageCopyToOutput>
		</Content>
		<None Include="..\readme.md;..\LICENSE" Pack="true" PackagePath="\" />
	</ItemGroup>
	
	<ItemGroup Condition="'$(DefineConstants.Contains(`LuceneSharp`))'">
		<PackageReference Include="Lucene.Net" Version="4.8.0-beta00017" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.FileProviders.Physical" Version="10.0.1" />
	</ItemGroup>
</Project>


